package test

import game.scene.PlayerEyePoints
import java.io.File
import javax.imageio.ImageIO
import kotlin.test.*

/**
 * PlayerEyePoints (generated by tools/art/prep_eyes.py) against the frames on disk: same count,
 * same order, and every eye on the front edge of a solid face - which is what catches a clip
 * re-cut without re-running the script (every later index would point into the wrong frame).
 */
class PlayerEyePointsTest {

    /** Folder, first file, frame count - GameplayScene.playerFrames order (PlayerAnimations.load()). */
    private val clips = listOf(
        Triple("idle", 1, 45), Triple("walk", 1, 40), Triple("jump", 1, 44), Triple("crouch", 1, 34),
        Triple("crouchwalk", 1, 144), Triple("climb", 70, 155), Triple("swing", 1, 52),
        Triple("pushtransition", 1, 32), Triple("push", 1, 40), Triple("windtransition", 1, 29),
        Triple("windwalk", 1, 25)
    )

    @Test
    fun testEveryFrameHasAnEyeOnTheFrontOfASolidFace() {
        assertEquals(clips.sumOf { it.third }, PlayerEyePoints.FRAME_COUNT)
        var i = 0
        var handAtFace = 0
        for ((folder, first, count) in clips) {
            for (n in first until first + count) {
                val img = ImageIO.read(File("resources/player/$folder/${n.toString().padStart(4, '0')}.png"))
                val x = PlayerEyePoints.x(i)
                val y = PlayerEyePoints.y(i)
                fun alpha(px: Int, py: Int) = if (px in 0 until img.width && py in 0 until img.height) (img.getRGB(px, py) ushr 24) and 0xFF else 0
                assertTrue(alpha(x, y) > 128, "$folder/$n: the eye ($x, $y) is on the silhouette")
                // Air just ahead of it - except where a hand or fist touches the face (the climb's
                // raised hands, the wind walk's fist), where the script stops at the face anyway.
                if (alpha(x + 1, y) > 128 && alpha(x + 2, y) > 128 && alpha(x + 3, y) > 128) handAtFace++
                // The head is in the top part of the figure in every pose, never down at the body.
                val solidRows = (0 until img.height).filter { r -> (0 until img.width).any { alpha(it, r) > 128 } }
                val figureTop = solidRows.first()
                val figureHeight = solidRows.last() - figureTop
                assertTrue(y - figureTop < figureHeight * 0.45, "$folder/$n: the eye ($x, $y) is up at the head")
                i++
            }
        }
        assertTrue(handAtFace < PlayerEyePoints.FRAME_COUNT / 20, "the eye is on the face's front edge, with air ahead, in almost every frame ($handAtFace without)")
    }
}
