"""
Measure where the operative's eye is in every player animation frame, and write the table to
src/game/scene/PlayerEyePoints.kt.

Usage:  python tools/art/prep_eyes.py

Why: level 9's figure (the echo) is drawn with the player's own frames, and its vision cone has to
start at the eye of the frame actually on screen - "make sure it follows correctly under every
position and in front of his eye". A single offset from the collision box cannot do that: the head
is somewhere else in every clip (leaning into a cart, hunched in a crouch walk, tipped back under
the climb's raised hands, hanging under the swing's arm). So the eye is measured off the pixels.

How, per frame (all frames face RIGHT; the scene mirrors them):

  * The head is found with a round probe, not by "topmost pixel". Raised hands (climb, swing) and
    the fist held up in front of the face (wind walk) reach as high as the head or higher, but they
    are thin: a disc of radius PROBE_RADIUS fits inside the head and not inside an arm. So the
    silhouette (alpha > 128) is eroded by that disc, and the head centre is the surviving point
    that maximises (-y + FORWARD_BIAS * x) - the highest, and in a hunched pose (where the back is
    as high as the head) the more forward one.
  * The eye is EYE_ABOVE_CENTRE above that centre, on the FRONT edge of the face: walking forward
    along that row from the centre to the last solid pixel, capped at FACE_REACH so a hand or fist
    touching the face is not mistaken for it. The cone therefore starts at the face, in front of
    the eye, not inside the skull.

Verified by rendering every clip with the point marked (a debug sheet is written with --sheet).
Re-run after any player clip is re-cut, and after changing which files a clip loads - the clip
list below mirrors PlayerAnimations.load() and GameplayScene's playerFrames order, which is what
the table is indexed by.
"""
import os
import sys

import numpy as np
from PIL import Image, ImageDraw

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'src', 'game', 'scene', 'PlayerEyePoints.kt')

PROBE_RADIUS = 10       # px in a 256-tall frame: inside a head (~26 across), wider than an arm
FORWARD_BIAS = 0.35     # how much "forward" is worth against "higher" when picking the head
EYE_ABOVE_CENTRE = 2    # px
FACE_REACH = PROBE_RADIUS + 8  # px past the head centre the face edge may be

# (folder, first file, frame count) in GameplayScene.playerFrames order - keep in step with
# PlayerAnimations.load() (the counts are its *_FRAMES constants; climb starts at CLIMB_FILE_START).
CLIPS = [
    ('idle', 1, 45),
    ('walk', 1, 40),
    ('jump', 1, 44),
    ('crouch', 1, 34),
    ('crouchwalk', 1, 144),
    ('climb', 70, 224 - 70 + 1),
    ('swing', 1, 52),
    ('pushtransition', 1, 32),
    ('push', 1, 40),
    ('windtransition', 1, 29),
    ('windwalk', 1, 25),
]


def disc_erode(solid, r):
    h, w = solid.shape
    pad = np.pad(solid, r, constant_values=False)
    out = np.ones_like(solid)
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            if dx * dx + dy * dy <= r * r:
                out &= pad[r + dy:r + dy + h, r + dx:r + dx + w]
    return out


def eye_of(solid):
    core = disc_erode(solid, PROBE_RADIUS)
    ys, xs = np.nonzero(core)
    if len(ys) == 0:
        ys, xs = np.nonzero(solid)
    i = int(np.argmax(-ys + FORWARD_BIAS * xs))
    cx, cy = int(xs[i]), int(ys[i])
    ey = cy - EYE_ABOVE_CENTRE
    row = solid[ey]
    x = cx
    while x + 1 < row.size and row[x + 1] and x + 1 <= cx + FACE_REACH:
        x += 1
    return x, ey, cx, cy


def main():
    sheet = '--sheet' in sys.argv
    points = []
    tiles = []
    for folder, first, count in CLIPS:
        for n in range(first, first + count):
            path = os.path.join(ROOT, 'resources', 'player', folder, f'{n:04d}.png')
            im = Image.open(path).convert('RGBA')
            solid = np.array(im)[:, :, 3] > 128
            x, y, cx, cy = eye_of(solid)
            points.append((x, y))
            if sheet and n % 5 == 1:
                tiles.append((f'{folder}{n}', im, (x, y)))
    lines = []
    for k in range(0, len(points), 8):
        chunk = points[k:k + 8]
        lines.append('        ' + ', '.join(f'{x}, {y}' for x, y in chunk) + ',')
    body = '\n'.join(lines).rstrip(',')
    ranges = []
    start = 0
    for folder, first, count in CLIPS:
        ranges.append(f' * - {folder}: {start}..{start + count - 1}')
        start += count
    kt = f'''package game.scene

// GENERATED by tools/art/prep_eyes.py - do not edit by hand; re-run it after re-cutting a clip.

/**
 * The operative's eye in every player animation frame, as (x, y) pixel pairs in the frame's own
 * space (frames face right), indexed like GameplayScene's `playerFrames` - every clip in
 * PlayerAnimations order, flattened:
{chr(10).join(ranges)}
 *
 * Measured off the pixels (head found with a round probe so raised hands and fists are skipped,
 * eye on the front edge of the face) - see the script's header. Level 9's figure starts its vision
 * cone here, so the beam follows the drawn head through every pose.
 */
object PlayerEyePoints {{
    const val FRAME_COUNT = {len(points)}

    private val XY = shortArrayOf(
{body}
    )

    fun x(frame: Int): Int = XY[frame * 2].toInt()
    fun y(frame: Int): Int = XY[frame * 2 + 1].toInt()
}}
'''
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(kt)
    print(f'{len(points)} frames -> {os.path.relpath(OUT, ROOT)}')
    if sheet:
        W, H, cols = 200, 300, 16
        rows = (len(tiles) + cols - 1) // cols
        out = Image.new('RGB', (W * cols, H * rows), (215, 215, 215))
        d = ImageDraw.Draw(out)
        for k, (name, im, (x, y)) in enumerate(tiles):
            ox, oy = (k % cols) * W, (k // cols) * H + (H - im.size[1])
            out.paste(im, (ox, oy), im)
            d.ellipse([ox + x - 3, oy + y - 3, ox + x + 3, oy + y + 3], outline=(255, 0, 0), width=2)
            d.line([ox + x, oy + y, ox + x + 40, oy + y], fill=(255, 0, 0), width=2)
            d.text((ox + 3, (k // cols) * H + 3), name, fill=(0, 0, 160))
        path = sys.argv[sys.argv.index('--sheet') + 1] if len(sys.argv) > sys.argv.index('--sheet') + 1 else 'eyes_sheet.png'
        out.save(path)
        print('sheet ->', path)


if __name__ == '__main__':
    main()
